#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

if test -z "${XYZ_TASK:-}"; then
  cat >&2 <<EOF
error: no task set, please run \`cv set-task ...'

The list of current tasks:
`print_tasks`
EOF
  exit 1
fi

