rem TODO: LLVM_ENABLE_EXPENSIVE_CHECKS=ON
rem -G "Visual Studio 14 2015 Win64"
rem -G "Visual Studio 15 2017 Win64" ^
rem -G "Visual Studio 16 2019" ^
rem -G "Visual Studio 15 2017 Win64" ^
cmake ^
  %* ^
  -G "Visual Studio 16 2019" ^
  -LLVM_PARALLEL_LINK_JOBS=1 ^
  -DLLVM_ENABLE_TERMINFO=OFF ^
  -DLLVM_INCLUDE_EXAMPLES=OFF ^
  -DCLANG_ENABLE_ARCMT=OFF ^
  -DCLANG_ENABLE_STATIC_ANALYZER=OFF ^
  -DLLVM_ENABLE_ASSERTIONS=ON ^
  -DXYZQ4_LLVM_SOURCE_DIR=../llvm ^
  -DXYZQ4_CLANG_SOURCE_DIR=../clang ^
  -DXYZQ4_COMPILER_RT_SOURCE_DIR=../compiler-rt ^
  -DXYZQ4_LIBC_SOURCE_DIR=../libc ^
  -DXYZQ4_LIBCXX_SOURCE_DIR=../libcxx ^
  -DXYZQ4_LIBUNWIND_SOURCE_DIR=../libunwind ^
  -DXYZQ4_LIBCXXABI_SOURCE_DIR=../libcxxabi ^
  -DXYZQ4_GCC_TESTS_LIT_TEST_DIR=../gcc_tests ^
  -DLLVM_TARGETS_TO_BUILD=MYTARGET ^
  ../XPLAY_LLVM

