rem Copyright 2026 Yury Gribov
rem 
rem Use of this source code is governed by MIT license that can be
rem found in the LICENSE.txt file.

%~dp0/cmake_vcvars.bat ^
  -G Ninja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_BUILD_TYPE=%CFG% ^
  -DCMAKE_VERBOSE_MAKEFILE=ON ^
  %* ^
  -LLVM_PARALLEL_LINK_JOBS=1 ^
  -DLLVM_ENABLE_TERMINFO=OFF ^
  -DLLVM_INCLUDE_EXAMPLES=OFF ^
  -DCLANG_ENABLE_ARCMT=OFF ^
  -DCLANG_ENABLE_STATIC_ANALYZER=OFF ^
  -DLLVM_ENABLE_ASSERTIONS=ON ^
  -DXYZQ4_LLVM_SOURCE_DIR=../llvm ^
  -DXYZQ4_CLANG_SOURCE_DIR=../clang ^
  -DXYZQ4_COMPILER_RT_SOURCE_DIR=../compiler-rt ^
  -DXYZQ4_LIBC_SOURCE_DIR=../libc ^
  -DXYZQ4_LIBCXX_SOURCE_DIR=../libcxx ^
  -DXYZQ4_LIBUNWIND_SOURCE_DIR=../libunwind ^
  -DXYZQ4_LIBCXXABI_SOURCE_DIR=../libcxxabi ^
  -DXYZQ4_GCC_TESTS_LIT_TEST_DIR=../gcc_tests ^
  -DLLVM_TARGETS_TO_BUILD=MYTARGET ^
  ../XPLAY_LLVM

