#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Remove Cygwin's stuff from PATH to force Perl from TFS

set -eu

#echo $PATH | sed -e 's!/\(usr\|bin\)[^:]*:\?!!g'
IFS=:
NEWPATH=
for d in $PATH; do
  if echo $d | grep -qv '^/\(usr\|bin\)'; then
    NEWPATH=${NEWPATH:+$NEWPATH:}$d
  fi
done
echo "$NEWPATH"
