#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

check_target_set

core=$(echo $XYZ_CORE | tr 'A-Z' 'a-z')
abi=$(echo $XYZ_ABI | tr 'A-Z' 'a-z')

echo xyz$core-unknown-unknown-$abi
