#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

case "$1" in
b)
  echo build-compiler
  ;;
s)
  echo set-task
  ;;
i)
  echo install-compiler
  ;;
u)
  echo unset-task
  ;;
sc | st | set-core)
  echo set-target
  ;;
z)
  echo zip-tools
  ;;
v)
  echo vim
  ;;
oi)
  echo open-isdb
  ;;
*)
  echo $1
  ;;
esac
