#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu
source set_paths

if test -d $XYZ_LLVM_ROOT/"$1"; then
  exit 0
fi

(echo $XYZ_INSTALL_ROOT/$1/*/xyztools/bin/clang.exe | grep -qv '\*') \
  || (echo $XYZ_INSTALL_ROOT/$1/*/xyztools/bin/xyz-elf-as.exe | grep -qv '\*')
