#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu
source set_paths

check_task_set

test -f $XYZ_LLVM_BUILD/build.ninja
