#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

CPU=$(grep -c '^processor' /proc/cpuinfo)

# Leave something to user
if test $CPU -gt 1; then
  CPU=$((CPU - 1))
fi

echo $CPU
