#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

if test -z "${XYZ_BATCH_MODE:-}"; then
  msg="Bash $$: ${1:-done}"
  msg $USER "$msg"
  rundll32 user32.dll,MessageBeep
fi
