#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu
source set_paths

ls -1 $XYZ_XTS_ROOT/Q4/builds | grep '^v' | sed 's/^v//'

