#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

# This will replace "\nXXX\$" in prompt with "\nTASK \$" (not too generic but enough for me)
echo "export PS1=\$(echo '$PS1___' | sed '"'s![\]n[^\]*[\]\$!\\n'"$1"'\\$!'\'') ;'
