#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

source colors

for d in $XYZ_LLVM_SOURCE/*; do
  if test -d "$d"/.git; then
    BRANCH=$(cd $d && git rev-parse --abbrev-ref HEAD | tr -d '\n')
    if test "${1:-}" = pretty -a $BRANCH != develop; then
      # Cygwin does not seem to support colors
      BRANCH="<<<$BRANCH>>>"
    fi
    HASH=$(cd $d && git rev-parse HEAD | tr -d '\n')
    echo "$d $BRANCH $HASH"
  fi
done
