#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

# Extract possible names from case statement inside cd.sh
grep 'TARGETS=' $(dirname $0)/get_sym_file \
  | sed "s/.*TARGETS='\\(.*\\)'$/\\1/" \
  | sed 's/[;,]/ /g' \
  | if test "${1:-}" = pretty; then
      sed 's/ \+/ /g' | tr ' ' '\n' | sed 's/^/  /g'
    else
      tr '();' '   '
    fi \
  | while read x; do echo $x; echo $x | tr A-Z a-z; done \
  | tr -d '\n'
