#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

# Remove tools from PATH to avoid side-effects
echo "$PATH" | sed 's![^:]*\/\(XYZ-\|xyztools\)[^:]*:!!g'
