#!/bin/sh

# Copyright 2026 Yury Gribov
#▫
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

tf history . /r /collection:http://codefront:8080/tfs/defaultcollection /noprompt /stopafter:1 /version:W
