#!/bin/sh

set -eu
shift
source set_paths

usage_short() {
  CMD=$(basename $0 .sh)
  cat >&2 <<EOF
Usage: cv build-compiler [OPT]... [CONFIG] [TARGET]
For more info run \`cv help $CMD'
EOF
  exit 1
}

usage() {
  cat >&2 <<EOF
Usage: cv build-compiler [OPT]... [CONFIG] [TARGET]

CONFIG can be one of $(get_config)
(Open64 allows only Release and Debug and their shortened versions d and r).
For LLVM default value is RelWithDebInfo for Ninja and Debug for VS.
For Open64 default is not defined.

Available options:
  -h, --help                  Print help and exit.
  -x                          Enable debug mode.
  -o, --only PRJ1,PRJ2,...    Build only some projects in solution.
  -n, --ninja                 Build Ninja instead of VS.
  -i, --install               Install after build.
  -r, --rebuild               Rebuild from scratch.
  -g, --regen                 Rebuild autogenerated code.
  -m, --minimal               Build only clang and libraries.
  -y, --yes                   Assume yes for all questions.
  -z, --zip                   Zip after build and install.
EOF
  exit
}

ARGS=$(getopt -o 'gmrihno:yxz' --long 'minimal,rebuild,install,only:,ninja,help,yes,zip,regen' -n $(basename $0) -- "$@")
eval set -- "$ARGS"

ONLY=
export NINJA=
INSTALL=
REBUILD=
YES=
ZIP=
REGEN=
while true; do
  case "$1" in
    -m | --minimal)
      ONLY='mytarget-runtime'
      shift
      ;;
    -o | --only)
      ONLY="$2"
      shift 2
      ;;
    -r | --rebuild)
      REBUILD=1
      shift
      ;;
    -y)
      YES=1
      shift
      ;;
    -i | --install)
      INSTALL=1
      shift
      ;;
    -g | --regen)
      REGEN=1
      shift
      ;;
    -h | --help)
      usage
      ;;
    -x)
      set -x
      shift
      ;;
    -n | --ninja)
      NINJA=1
      shift
      ;;
    -z | --zip)
      ZIP=1
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      error "unknown option: $1"
      ;;
    *)
      error 'internal error'
      ;;
  esac
done

check_task_set
check_target_set

if test -n "${VSINSTALLDIR:-}"; then
  echo >&2 "warning: VSINSTALLDIR environment variable is set, this may cause issues during build"
  exit 1
fi

if test $# -eq 0; then
  if is_llvm_task $XYZ_TASK; then
    if test -z "$NINJA"; then
      CONFIG=Debug
    else
      CONFIG=RelWithDebInfo
    fi
  else
    echo >&2 "Open64 builds require config (Debug or Release)"
    exit 1
  fi
elif test $# -eq 1; then
  CONFIG=$(get_config $1)
  test -z "$INSTALL" || check_target_set
elif test $# -eq 2; then
  CONFIG=$(get_config $1)
  source cv set-target $2
else
  usage_short
fi

if test -n "$ZIP" -a -z "$INSTALL"; then
  echo >&2 "--zip can not be enabled without --install"
  exit 1
fi

check_task_set

TMP=$(mktemp -d)
TRAP_CMD="rm -rf $TMP"
TRAP_NOTIFY=1
. setup_atexit

# Remove Cygwin from PATH to use ActivePerl and Windows Python
NEW_PATH=$(filter_cygwin_path)

maybe_rm() {
  if test -n "$REBUILD"; then
    if test -z "$YES"; then
      echo -n "Ok to remove $B (y/n)? "
      read yesno
    else
      yesno=y
    fi
    case $yesno in
    Y | Yes | y | yes)
      rm -rf $B
      ;;
    N | No | n | no)
      echo 'Ignoring --rebuild per user request.'
      ;;
    *)
      echo >&2 "Unknown reply '$yesno', aborting..."
      exit 1
      ;;
    esac
  fi
}

if is_llvm_task $XYZ_TASK; then
  if test -n "$NINJA"; then
    B=$XYZ_LLVM_BUILD-ninja-$CONFIG
    maybe_rm $B
    if ! test -f $B/build.ninja; then
      echo "Generating $B folder..."
      (cd $XYZ_LLVM_SOURCE && cmd /c configure-ninja.bat $CONFIG)
    fi
  else
    B=$XYZ_LLVM_BUILD
    maybe_rm $B
    if ! test -d $B; then
      echo "Generating $B folder..."
      (cd $XYZ_LLVM_SOURCE && cmd /c configure.bat $CONFIG)
    fi
  fi
fi

cmake_build() {
#  export CMAKE_BUILD_PARALLEL_LEVEL=1
  if test -n "$NINJA"; then
    # Ninja build is more complicated because we need to load VS environment
    (
      cd $B
      source cv unset-task
      set
      PATH="$NEW_PATH" cmd /c "$(cygpath -w $XYZ_HELPERS)/cmake_vcvars.bat --build . $@"
    )
  else
    (
      cd $B
      source cv unset-task
      PATH="$NEW_PATH" /usr/bin/nice cmake --build . --config $CONFIG "$@"
    )
  fi
}

devenv_build() {
  PATH="$NEW_PATH" /usr/bin/nice "$DEVENV" $@ /rebuild $CONFIG /log $DEVENV_FLAGS
}

if is_llvm_task $XYZ_TASK; then
  if test -n "$REGEN"; then
    MYTARGETB=$(get_sym_dir targb)
    ! test -n "$MYTARGETB" || rm -f $MYTARGETB/{*.inc,*.tmp,*.json,*.td}
  fi
  DEVENV=$MSVS14/devenv
  if test -n "$ONLY"; then
    if echo "$ONLY" | grep -q 'all-headers'; then
      check_target_set
      core=$(echo $XYZ_CORE | tr 'A-Z' 'a-z')
      ONLY=$(echo "$ONLY" | sed "s/all-headers/libc-include-headers-XYZ$core-unknown-unknown-elf,clang-headers/")
      case $XYZ_CORE in
      S* | Q8 | P16)
        ONLY="$ONLY,libc-comp-headers-XYZ$core-unknown-unknown-elf"
        ;;
      esac
    fi
    for PRJ in $(echo "$ONLY" | tr ',' ' '); do
      echo "Building $B/$PRJ (\"$CONFIG\" config)..."
#      if ! (cd $XYZ_LLVM_BUILD && devenv_build /Project $PRJ); then
      if ! cmake_build --target $PRJ; then
        echo "BUILD FAILED"
        exit 1
      fi
    done
  else
    echo "Building $B (\"$CONFIG\" config)..."
    if ! cmake_build; then
      echo "BUILD FAILED"
      exit 1
    fi
  fi
else
  check_target_set

  if test -n "$ONLY"; then
    echo >&2 'Option --only not yet supported for Open64'
    exit 1
  fi

  # Ignore installed files
  TMP=$(cygpath -w $TMP)
  export XYZRTOOLS="$TMP"
  export XYZPTOOLS="$TMP"
  export XYZP12TOOLS="$TMP"
  export Q4TOOLS="$TMP"
  export XYZQTOOLS="$TMP"
  export XYZQ6TOOLS="$TMP"
  export Q6TOOLS="$TMP"

  case $XYZ_CORE in
  Q4)
    CONFIG="${CONFIG}_QQ|Win32"
    ;;
  *)
    CONFIG="${CONFIG}_${XYZ_CORE}|Win32"
    ;;
  esac

  DEVENV=$MSVS10/devenv
  PRJ=XYZ_Open64.sln
  DEVENV_FLAGS="/out build-tools.log"

  cd $XYZ_O64_BUILD

  if test -n "$ONLY"; then
    for PRJ in $(echo "$ONLY" | tr ',' ' '); do
      echo "Building $PWD/$PRJ (\"$CONFIG\" config)..."
      if ! devenv_build /Project $PRJ; then
        cat build-tools.log
        echo "BUILD FAILED"
        exit 1
      fi
    done
  else
    echo "Building $PWD/$PRJ (\"$CONFIG\" config)..."
    if ! devenv_build; then
      cat build-tools.log
      echo "BUILD FAILED"
      exit 1
    fi
  fi
fi

echo "BUILD SUCCEEDED"

TRAP_NOTIFY=  # Disable duplicate mboxes for install and zip

if test -n "$INSTALL"; then
  if test -n "$NINJA"; then
    NINJA=--ninja
  fi
  cv install-compiler $NINJA $CONFIG
fi

if test -n "$ZIP"; then
  cv zip-tools
fi
